[package]
name = "shell"
version = "0.1.0"
edition = "2024"
build = "src/build.rs"

[dependencies]
chrono = "0.4.42"
colored = "3.0.0"
futures = "0.3.31"
getopts = "0.2.24"
pathdiff = "0.2.3"
signal-hook = "0.3.18"
tokio = { version = "1.47.1", features = ["full"] }
